apiVersion: v2
appVersion: 0.0.1
name: coredns-extensions
description: Extra resources for CoreDNS
home: https://github.com/giantswarm/coredns-extensions-app
icon: https://s.giantswarm.io/app-icons/coredns/1/dark.svg
sources:
  - https://github.com/giantswarm/coredns-extensions-app
version: 0.1.2
annotations:
  io.giantswarm.application.team: cabbage
  io.giantswarm.application.audience: "all"
  io.giantswarm.application.managed: "false"
